# Generator for test/data/scftopo_golden.jl, the pinned ("golden") outputs of the SCF,
# superconductivity, purification and topology code and of the TBSystem mutators,
# checked by test/golden_scftopo.jl.
#
# Reference: generated from commit 1a5548b ("Run the third-round audit regression
# tests from runtests.jl", branch Anouar), before the Tier 1 code reorganisation
# (docs/dev/REORGANISATION_TODO.md). The data pins what the code does at that commit,
# remaining bugs included.
#
# The cases themselves are defined in test/golden_scftopo.jl (module ScftopoGolden),
# which this script includes with SCFTOPO_GOLDEN_GENERATOR defined so that only the
# module is loaded. Each case is run in a fixed order with the global RNG seeded from
# its name; its value (MPOs/MPSs reduced to dense matrices/vectors) or the exception
# it throws is written with `repr`, which round-trips Float64/ComplexF64 exactly.
#
# Line 4 of the data file records the git tree hash of the working-tree src/, i.e.
# the src/ that the regenerating commit will contain.
#
# Regenerate ONLY when a behaviour change is intentional. Do it in the same commit as
# the change, review the diff of scftopo_golden.jl case by case, and record the change
# in the changelog. A refactor that is meant to leave outputs alone must pass
# test/golden_scftopo.jl against the existing data unchanged.
#
# How to run, from the repository root with the package environment:
#
#     JULIA_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 julia --project=. test/data/generate_scftopo_golden.jl
#
# The script reloads the file it wrote and checks that every entry round-trips with
# identical values and leaf types.

using TensorBinding, ITensors, ITensorMPS, LinearAlgebra, Test, Random

const SCFTOPO_GOLDEN_GENERATOR = true
include(joinpath(@__DIR__, "..", "golden_scftopo.jl"))   # loads ScftopoGolden only
const G = ScftopoGolden

const OUTFILE = joinpath(@__DIR__, "scftopo_golden.jl")

# The git tree hash of the working-tree src/, computed through a throwaway index.
function src_info()
    index = tempname()
    try
        repo = normpath(joinpath(@__DIR__, "..", ".."))
        tree = withenv("GIT_INDEX_FILE" => index) do
            run(`git -C $repo read-tree HEAD`)
            run(`git -C $repo add -A -- src`)
            readchomp(`git -C $repo write-tree --prefix=src/`)
        end
        return "src/ tree $(first(tree, 12))"
    catch
        return "an unknown src/ tree (not a git checkout)"
    finally
        rm(index; force = true)
    end
end

function evaluate(cases)
    entries = []
    for (name, f) in cases
        t = @elapsed r = G.run_case(name, f)
        push!(entries, (; name, throws = r.throws, expected = r.expected))
        status = r.throws === nothing ? "value" : "throws $(r.throws): $(r.expected.message_prefix)"
        println(rpad(name, 72), lpad(string(round(t; digits = 2)), 7), " s  ", status)
    end
    return entries
end

function write_golden(path, entries)
    source = src_info()
    open(path, "w") do io
        println(io, "# AUTO-GENERATED by test/data/generate_scftopo_golden.jl -- do not edit by hand.")
        println(io, "#")
        println(io, "# Pinned outputs of SCF/Supercond/Purification/Topology and the TBSystem mutators.")
        println(io, "# Generated from $source")
        println(io, "# with Julia $VERSION. Regenerate only for an intentional behaviour change;")
        println(io, "# see the generator's header.")
        println(io, "#")
        println(io, "# Each entry is (name, throws, expected): `name` selects a case of")
        println(io, "# ScftopoGolden.CASES (test/golden_scftopo.jl); `throws` is the name of the")
        println(io, "# exception type a failing case must still raise (otherwise `nothing`); `expected`")
        println(io, "# is the case's value, or for a throwing case the first $(G.MESSAGE_PREFIX_CHARS) characters of")
        println(io, "# its message (`message_prefix`, `nothing` when the exception has no message).")
        println(io, "#")
        println(io, "# $(length(entries)) cases, $(count(e -> e.throws !== nothing, entries)) of them pinned as throwing.")
        println(io)
        println(io, "SCFTOPO_GOLDEN_CASES = Any[]")
        for e in entries
            println(io)
            println(io, "push!(SCFTOPO_GOLDEN_CASES, (name = ", repr(e.name), ", throws = ", repr(e.throws), ",")
            println(io, "    expected = ", repr(e.expected), "))")
        end
        println(io)
        println(io, "SCFTOPO_GOLDEN_CASES")
    end
end

total = @elapsed entries = evaluate(G.CASES)
write_golden(OUTFILE, entries)

# Round trip: every entry must read back with identical values and leaf types.
loaded = include(OUTFILE)
length(loaded) == length(entries) ||
    error("round trip: $(length(loaded)) entries read back, $(length(entries)) written")
for (a, b) in zip(loaded, entries)
    a.name == b.name && a.throws == b.throws && G.identical(a.expected, b.expected) ||
        error("round trip failed for case $(b.name)")
end

println("Wrote $(length(entries)) cases ($(count(e -> e.throws !== nothing, entries)) throwing) to ",
        "$OUTFILE ($(filesize(OUTFILE)) bytes) in $(round(total; digits = 1)) s")
