# Generator for test/data/qft_golden.jl, the pinned ("golden") outputs of
# src/physics/qft/ (the former src/physics/QFT_tk.jl), checked by test/golden_qft.jl.
#
# Reference: first generated from commit 1a5548b ("Run the third-round audit
# regression tests from runtests.jl"), before Tier 1 of the code-organisation
# refactor (docs/dev/REORGANISATION_TODO.md). The data pin what the code does
# at that commit, remaining bugs included. The 2026-09 bug pass regenerated the
# cases its fixes moved (87f6562: the 2D k-space window and empty groups; 4954a37:
# the aux projections, with new postpended-spin and BdG+spin cases).
#
# Line 4 of the data file records the git tree hash of the working-tree src/,
# i.e. the src/ that the regenerating commit will contain. It does not move when
# only tests or docs change, so such a rerun reproduces the file byte for byte.
#
# Regenerate ONLY when a behaviour change is intentional. Do it in the same
# commit as the change, review the diff of qft_golden.jl case by case, and
# record the change in the changelog. A refactor that is meant to leave outputs
# alone must pass test/golden_qft.jl against the existing data unchanged.
#
# How to run, from the repository root with the package environment:
#
#     JULIA_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 julia --project=. test/data/generate_qft_golden.jl
#
# An optional first argument writes the data to that path instead, e.g. to
# compare a regeneration with the committed file without overwriting it.
#
# Cases marked `requires` whose functions have been deleted are not run and are
# left out of the data; test/golden_qft.jl skips them whether or not the data
# still holds them.
#
# The cases, fixtures and the comparison live in test/golden_qft.jl (module
# QFTGoldenRunner); this script only runs them and writes the results. The
# output is deterministic: no timestamps, cases in the order they are defined,
# values written with `repr` (which round-trips Float64/ComplexF64 exactly). The
# script reloads the file it wrote and checks that every entry reads back
# identical, with identical types.

using TensorBinding

const QFT_GOLDEN_GENERATOR = true
include(joinpath(@__DIR__, "..", "golden_qft.jl"))   # loads QFTGoldenRunner only
const RUNNER = QFTGoldenRunner

const OUTFILE = isempty(ARGS) ? joinpath(@__DIR__, "qft_golden.jl") : abspath(ARGS[1])

function evaluate(cases)
    names = [c.name for c in cases]
    allunique(names) || error("duplicate case names: $(unique(filter(n -> count(==(n), names) > 1, names)))")
    # A case whose `requires` functions have been deleted has nothing left to pin.
    for case in cases
        RUNNER.available(case) || println("skipped, function deleted: ", case.name)
    end
    empty!(RUNNER.FIXTURES)
    entries = NamedTuple[]
    for case in filter(RUNNER.available, cases)
        t = time()
        value, err = try
            (RUNNER.run_case(case), nothing)
        catch e
            (nothing, e)
        end
        if err === nothing
            case.throws && error("case $(case.name) is declared `throws=true` but returned normally")
            push!(entries, (; name = case.name, throws = nothing, expected = value))
        else
            case.throws || error("case $(case.name) threw $(typeof(err)): $(sprint(showerror, err))")
            push!(entries, (; name = case.name, throws = typeof(err),
                            expected = (; message_prefix = RUNNER.message_prefix(err))))
        end
        println(rpad(case.name, 58), lpad(round(time() - t; digits=2), 7), " s",
                err === nothing ? "" : "  throws $(typeof(err))")
    end
    return entries
end

# The git tree hash of the working-tree src/, computed through a throwaway index.
# Data are regenerated in the same commit as the behaviour change, so this is the
# src/ of that commit; a commit id could not be recorded inside its own commit.
function src_info()
    index = tempname()
    try
        repo = normpath(joinpath(@__DIR__, "..", ".."))
        tree = withenv("GIT_INDEX_FILE" => index) do
            run(`git -C $repo read-tree HEAD`)
            run(`git -C $repo add -A -- src`)
            readchomp(`git -C $repo write-tree --prefix=src/`)
        end
        return "src/ tree $(first(tree, 12))"
    catch
        return "an unknown src/ tree (not a git checkout)"
    finally
        rm(index; force=true)
    end
end

# FieldError exists from Julia 1.12; before that the same access throws an ErrorException.
_throws_repr(T) = T === nothing ? "nothing" :
    nameof(T) === :FieldError ? "(isdefined(Core, :FieldError) ? Core.FieldError : ErrorException)" :
    repr(T)

function write_golden(path, entries)
    source = src_info()
    open(path, "w") do io
        println(io, "# AUTO-GENERATED by test/data/generate_qft_golden.jl -- do not edit by hand.")
        println(io, "#")
        println(io, "# Pinned outputs of src/physics/qft/, checked by test/golden_qft.jl.")
        println(io, "# Generated from $source")
        println(io, "# with Julia $VERSION. Regenerate only for an intentional behaviour change;")
        println(io, "# see the generator's header.")
        println(io, "#")
        println(io, "# Each entry is (name, throws, expected): `name` selects the case of the same")
        println(io, "# name in QFTGoldenRunner.CASES (same order), `throws` is the exception type a")
        println(io, "# failing case must still raise (otherwise `nothing`), and `expected` holds")
        println(io, "# every field the case returned plus its captured `stdout` or, for a throwing")
        println(io, "# case, the first $(RUNNER.MESSAGE_PREFIX_CHARS) characters of its message (`message_prefix`,")
        println(io, "# `nothing` when the exception has no message).")
        println(io, "#")
        println(io, "# $(length(entries)) cases, $(count(e -> e.throws !== nothing, entries)) of them pinned as throwing.")
        println(io)
        println(io, "QFT_GOLDEN_CASES = Any[]")
        for e in entries
            println(io)
            println(io, "push!(QFT_GOLDEN_CASES, (name = ", repr(e.name), ", throws = ", _throws_repr(e.throws), ",")
            println(io, "    expected = ", repr(e.expected), "))")
        end
        println(io)
        println(io, "QFT_GOLDEN_CASES")
    end
end

t0 = time()
entries = evaluate(RUNNER.CASES)
write_golden(OUTFILE, entries)

# Round trip: every entry must read back exactly as it was computed, with the
# same types (element types included) that test/golden_qft.jl compares.
loaded = include(OUTFILE)
length(loaded) == length(entries) ||
    error("round trip: $(length(loaded)) entries read back, $(length(entries)) written")
for (a, b) in zip(loaded, entries)
    (a.name == b.name && a.throws === b.throws) || error("round trip failed for case $(b.name)")
    typeof(a.expected) == typeof(b.expected) ||
        error("round trip changed the type of $(b.name).expected: $(typeof(a.expected)) != $(typeof(b.expected))")
    isequal(a.expected, b.expected) || error("round trip changed the values of $(b.name)")
end

println("Wrote $(length(entries)) cases ($(count(e -> e.throws !== nothing, entries)) throwing) to $OUTFILE ",
        "($(filesize(OUTFILE)) bytes) in $(round(time() - t0; digits=1)) s")
