# Generator for test/data/dynamics_golden.jl, the pinned ("golden") outputs of
# the dynamics area, checked by test/golden_dynamics.jl.
#
# Reference: the golden data was first generated from commit 1a5548b ("Run the
# third-round audit regression tests from runtests.jl", branch Anouar), before
# Tier 1 of the code-organisation refactor (docs/dev/REORGANISATION_TODO.md). It
# pins what the code computes there, remaining bugs included. The 2026-09 bug pass
# regenerated the cases its fixes moved (87f6562: fix_sites, the one-site MPS;
# ead1d66: Haydock; a64b949: the TwoParticle cases).
#
# The cases themselves (inputs, seeds and which outputs are recorded) live in
# DynamicsGoldenRunner in test/golden_dynamics.jl, so that the test and this
# generator run exactly the same code. This script runs every case once, in one
# Julia process, and writes the results as plain Julia literals.
#
# Line 4 of the data file records the git tree hash of the working-tree src/,
# i.e. the src/ that the regenerating commit will contain. It does not move when
# only tests or docs change, so such a rerun reproduces the file byte for byte
# (floating-point results are written with `repr`, which round-trips exactly).
#
# Regenerate ONLY when a behaviour change is intentional. Do it in the same
# commit as the change, review the diff of dynamics_golden.jl case by case, and
# record the change in the changelog. A refactor that is meant to leave outputs
# alone must pass test/golden_dynamics.jl against the existing data unchanged.
#
# How to run, from the repository root with the package environment:
#
#     JULIA_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 julia --project=. test/data/generate_dynamics_golden.jl
#
# The script reloads the file it wrote, checks that every entry round-trips
# exactly (values and element types), and replays the test against it.

using TensorBinding, ITensors, ITensorMPS, LinearAlgebra, Test, Random

const DYNAMICS_GOLDEN_GENERATOR = true
include(joinpath(@__DIR__, "..", "golden_dynamics.jl"))   # loads DynamicsGoldenRunner only

const R = DynamicsGoldenRunner
const OUTFILE = joinpath(@__DIR__, "dynamics_golden.jl")

# An exception of one of these types means the case itself is malformed (a
# misspelt keyword, a wrong argument type), not a behaviour worth pinning.
const GENERATOR_BUGS = (MethodError, UndefVarError, UndefKeywordError, TypeError)

function evaluate(cases)
    names = [c.name for c in cases]
    allunique(names) || error("duplicate case names: $(unique(filter(n -> count(==(n), names) > 1, names)))")
    entries = NamedTuple[]
    notes = String[]
    for case in cases
        timed = @timed R.run_case(case)
        value, err = timed.value
        if err !== nothing
            any(T -> err isa T, GENERATOR_BUGS) && throw(err)
            push!(notes, "throws $(typeof(err)): $(case.name) -- $(first(sprint(showerror, err), 120))")
            push!(entries, (; name = case.name, group = case.group, seed = case.seed,
                            throws = typeof(err), expected = (; message_prefix = R.message_prefix(err))))
        else
            value isa NamedTuple || error("case $(case.name) returned a $(typeof(value)), not a NamedTuple")
            push!(entries, (; name = case.name, group = case.group, seed = case.seed,
                            throws = nothing, expected = value))
        end
        println(rpad(case.name, 56), lpad(string(round(timed.time; digits=2)), 8), " s  (compile ",
                round(timed.compile_time; digits=2), " s)")
    end
    return entries, notes
end

# The git tree hash of the working-tree src/, computed through a throwaway index.
# Data are regenerated in the same commit as the behaviour change, so this is the
# src/ of that commit; a commit id could not be recorded inside its own commit.
function src_info()
    index = tempname()
    try
        repo = normpath(joinpath(@__DIR__, "..", ".."))
        tree = withenv("GIT_INDEX_FILE" => index) do
            run(`git -C $repo read-tree HEAD`)
            run(`git -C $repo add -A -- src`)
            readchomp(`git -C $repo write-tree --prefix=src/`)
        end
        return "src/ tree $(first(tree, 12))"
    catch
        return "an unknown src/ tree (not a git checkout)"
    finally
        rm(index; force=true)
    end
end

function write_golden(path, entries)
    source = src_info()
    open(path, "w") do io
        println(io, "# AUTO-GENERATED by test/data/generate_dynamics_golden.jl -- do not edit by hand.")
        println(io, "#")
        println(io, "# Pinned outputs of the dynamics area, checked by test/golden_dynamics.jl.")
        println(io, "# Generated from $source")
        println(io, "# with Julia $VERSION. Regenerate only for an intentional behaviour change;")
        println(io, "# see the generator's header.")
        println(io, "#")
        println(io, "# Each entry is (name, group, seed, throws, expected): the case of that name in")
        println(io, "# DynamicsGoldenRunner.CASES is run after Random.seed!(seed); `throws` is the")
        println(io, "# exception type a failing case must still raise (otherwise `nothing`), and")
        println(io, "# `expected` holds every recorded output or, for a throwing case, the first")
        println(io, "# $(R.MESSAGE_PREFIX_CHARS) characters of its message (`message_prefix`, `nothing` when the")
        println(io, "# exception has no message).")
        println(io, "#")
        println(io, "# $(length(entries)) cases, $(count(e -> e.throws !== nothing, entries)) of them pinned as throwing.")
        println(io)
        println(io, "DYNAMICS_GOLDEN_CASES = Any[]")
        for e in entries
            println(io)
            println(io, "push!(DYNAMICS_GOLDEN_CASES, (name = ", repr(e.name), ", group = ", repr(e.group),
                    ", seed = ", repr(e.seed), ", throws = ", repr(e.throws), ",")
            println(io, "    expected = ", repr(e.expected), "))")
        end
        println(io)
        println(io, "DYNAMICS_GOLDEN_CASES")
    end
end

# Exact equality including element types at every nesting level.
function same(a, b)
    typeof(a) == typeof(b) || return false
    a isa NamedTuple && return keys(a) == keys(b) && all(k -> same(a[k], b[k]), keys(a))
    a isa AbstractArray && return size(a) == size(b) && all(i -> same(a[i], b[i]), eachindex(a, b))
    return isequal(a, b)
end

t_start = time()
entries, notes = evaluate(R.CASES)
foreach(println, notes)
write_golden(OUTFILE, entries)

loaded = include(OUTFILE)
length(loaded) == length(entries) || error("round trip: $(length(loaded)) entries read back, $(length(entries)) written")
for (a, b) in zip(loaded, entries)
    (a.name == b.name && a.seed == b.seed && a.throws === b.throws && same(a.expected, b.expected)) ||
        error("round trip failed for case $(b.name)")
end

println("Wrote $(length(entries)) cases to $OUTFILE ($(filesize(OUTFILE)) bytes) in $(round(time() - t_start; digits=1)) s")
for g in R.groups()
    println("  ", rpad(g, 14), count(e -> e.group == g, entries))
end
length(entries) == R.EXPECTED_CASE_COUNT ||
    @warn "The case count differs from EXPECTED_CASE_COUNT in test/golden_dynamics.jl. " *
          "If the change is intended, update it in the same commit." got = length(entries) expected = R.EXPECTED_CASE_COUNT

# Replay the test against the file just written (same process, so it also
# checks that every case is deterministic under its seed).
R.run_tests(loaded)
