# Generator for test/data/gpu_golden.jl, the pinned ("golden") outputs of the
# GPU entry points in src/gpu/*.jl, checked by test/golden_gpu.jl.
#
# Reference: first generated from commit 1a5548b ("Run the third-round audit
# regression tests from runtests.jl") on branch Anouar, before the Tier 1 code
# reorganisation (docs/dev/REORGANISATION_TODO.md). The data pins what the GPU
# code computes at that commit, suspected bugs included.
#
# The cases (inputs, calls, tolerances and the CPU counterparts) are defined in
# the GPUGoldenRunner module of test/golden_gpu.jl, which this script includes.
# For every case it
#   1. runs the GPU call and records its output (`gpu`);
#   2. runs the GPU call a second time and requires the two runs to agree within
#      the case tolerance (GPU arithmetic is not bit-reproducible);
#   3. runs the CPU counterpart, when there is one, and requires it to agree with
#      the GPU output within the case's `cpu_rtol`/`cpu_atol`; its output is
#      recorded as `cpu`, so the test compares against it without rerunning it.
# It then writes the data file with `repr`, reloads it and checks that every entry
# round-trips exactly (values and types).
#
# Regenerate ONLY when a behaviour change is intentional. Do it in the same
# commit as the change and review the diff of gpu_golden.jl case by case. A
# refactor that is meant to leave outputs alone must pass test/golden_gpu.jl
# against the existing data unchanged.
#
# Needs a functional CUDA.jl (loadable from the stacked default environment).
# How to run, from the repository root:
#
#     JULIA_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 julia --project=. test/data/generate_gpu_golden.jl
#
# The output is deterministic up to GPU rounding: cases in a fixed order, no
# timestamps.

using TensorBinding, ITensors, ITensorMPS, LinearAlgebra, Test, Random
using CUDA

CUDA.functional() || error("generate_gpu_golden.jl needs a functional CUDA.jl.")

const GPU_GOLDEN_GENERATOR = true
include(joinpath(@__DIR__, "..", "golden_gpu.jl"))   # loads GPUGoldenRunner only
const R = GPUGoldenRunner

const OUTFILE = joinpath(@__DIR__, "gpu_golden.jl")

function evaluate(c)
    t0 = time()
    gpu = R.run_gpu(c)
    t_gpu = time() - t0
    if c.throws
        gpu.exception === :none && error("case $(c.name) is marked `throws` but did not throw")
    end
    again = R.run_gpu(c)
    m = R.mismatch(again, gpu; rtol = c.rtol, atol = c.atol)
    m === nothing || error("case $(c.name) is not reproducible within its tolerance: $m")
    cpu = R.run_cpu(c)
    if cpu !== nothing
        mc = R.mismatch(gpu, cpu; rtol = c.cpu_rtol, atol = c.cpu_atol, strict = false)
        mc === nothing || error("case $(c.name): GPU and CPU disagree: $mc")
    end
    println(rpad(c.name, 52), " gpu ", lpad(round(t_gpu; digits = 2), 6), " s",
            cpu === nothing ? "  (no CPU counterpart)" : "")
    return (name = c.name, gpu = gpu, cpu = cpu)
end

function src_tree()
    repo = normpath(joinpath(@__DIR__, "..", ".."))
    try
        dirty = !isempty(readchomp(`git -C $repo status --porcelain -- src`))
        tree = readchomp(`git -C $repo rev-parse --short=12 HEAD:src`)
        return dirty ? "$tree (plus uncommitted changes)" : tree
    catch
        return "unknown"
    end
end

function write_golden(path, entries)
    dev = CUDA.name(CUDA.device())
    open(path, "w") do io
        println(io, "# AUTO-GENERATED by test/data/generate_gpu_golden.jl -- do not edit by hand.")
        println(io, "#")
        println(io, "# Pinned outputs of the GPU entry points (src/gpu/*.jl), checked by")
        println(io, "# test/golden_gpu.jl. Generated from src/ tree ", src_tree())
        println(io, "# with Julia ", VERSION, ", CUDA.jl ", pkgversion(CUDA), " on ", dev, ".")
        println(io, "# Regenerate only for an intentional behaviour change; see the generator's header.")
        println(io, "#")
        println(io, "# Each entry is (name, gpu, cpu): `gpu` is the GPU output of the case of that")
        println(io, "# name in GPUGoldenRunner.CASES, `cpu` the output of its CPU counterpart")
        println(io, "# (`nothing` when there is none). MPS/MPO outputs are dense vectors/matrices.")
        println(io, "# A throwing case records (exception, message_prefix).")
        println(io, "#")
        println(io, "# ", length(entries), " cases, ", count(e -> e.cpu !== nothing, entries),
                " of them with a CPU counterpart.")
        println(io)
        println(io, "GPU_GOLDEN_CASES = Any[]")
        for e in entries
            println(io)
            println(io, "push!(GPU_GOLDEN_CASES, (name = ", repr(e.name), ",")
            println(io, "    gpu = ", repr(e.gpu), ",")
            println(io, "    cpu = ", repr(e.cpu), "))")
        end
        println(io)
        println(io, "GPU_GOLDEN_CASES")
    end
end

function same_exactly(a, b)
    typeof(a) == typeof(b) || return false
    return isequal(a, b)
end

t_all = time()
entries = [evaluate(c) for c in R.CASES]
write_golden(OUTFILE, entries)

loaded = include(OUTFILE)
length(loaded) == length(entries) || error("round trip: $(length(loaded)) entries read back, $(length(entries)) written")
for (e, l) in zip(entries, loaded)
    (e.name == l.name && same_exactly(e.gpu, l.gpu) && same_exactly(e.cpu, l.cpu)) ||
        error("round trip failed for case $(e.name)")
end
println("wrote ", length(entries), " cases to ", OUTFILE, " (", filesize(OUTFILE), " bytes) in ",
        round(time() - t_all; digits = 1), " s; round trip exact")
